name: "Sponsor CAP (no-strings)"
description: Initiate a no-strings sponsorship discussion
labels: ["sponsor"]
title: "Sponsor CAP — <Your Org>"
body:
  - type: input
    id: org
    attributes: { label: Organization name }
    validations: { required: true }
  - type: input
    id: contact
    attributes: { label: Contact (name + email) }
    validations: { required: true }
  - type: textarea
    id: intent
    attributes: { label: Intent (note: sponsorship confers no governance control), placeholder: "Why you want to sponsor CAP…" }
    validations: { required: true }
  - type: dropdown
    id: public
    attributes: { label: Public listing OK?, options: ["Yes","No"] }
    validations: { required: true }
