name: link-check
on:
  schedule: [{ cron: '0 7 1 * *' }]
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --config .lychee.toml --verbose --no-progress --max-redirects 10 './**/*.md' './**/*.html'
      - name: Save report
        if: always()
        run: |
          mkdir -p reports
          cp ./lychee/out.md reports/link-check.md || true
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: link-check-report
          path: reports/link-check.md
